### ISSUE TITLE
How to use the web-components plugin?

### ISSUE THREAD

**Issue by Renaud009** [aurelia/web-components#2]
I would be interested in using the web-components plugin to generate standards-compliant Web Components from an Aurelia component just like Polymer does 'naturally'.

The plugin hasn't been published on npm or anywhere. He is ready to be used? Will he be anytime soon? I'm not quite sure how to import and use it too. Can you help me?

Thank you,

Renaud

**Comment by EisenbergEffect** [comment]
The specs were recently changed. We need to update this a bit to align with the specs. This plugin doesn't contain a polyfill for the Custom Element spec itself though. It only enables Aurelia Elements to be registered as custom elements, assuming that capability is present. We haven't decided yet if we want to create our own polyfill, or if we should wait for someone else to create one. I don't currently know of any existing polyfill for the updated specs.

**Comment by AStoker** [comment]
Do we have an updated status on Aurelia working the web components spec?
