### ISSUE TITLE
<template> displayed in DOM

### ISSUE THREAD

**Issue by Tim-Erwin** [aurelia/web-components#6]
**I'm submitting a bug report**

* **Library Version:**
0.1.0

**Please tell us about your environment:**
* **Operating System:**
OSX 10.13.4

* **Node Version:**
8.9.4

* **NPM Version:**
5.8.0

* **Browser:**
Firefox 59

* **Language:**
TypeScript

**Current behavior:**
Thanks for the quick support with #4. Exposing the app itself as webcomponent seems like an obvious and useful thing to do. However, I'd like to take an element and use it as a webcomponent.

Starting from the project in #4 I added `my-component` to the global resources. Also I added a little bit of static content to the template of `my-component` so that the following is more obvious: the "empty" template is display in the final document.

The zipped project (as usual without `node_modules`) is here: 
[comptest.zip](https://github.com/aurelia/web-components/files/1974565/comptest.zip) (I also added a poly fill because I'm using Firefox.)

That's how it looks like:

<img width="280" alt="bildschirmfoto 2018-05-04 um 15 30 58" src="https://user-images.githubusercontent.com/802148/39630669-4c0dffb2-4fb0-11e8-886d-94402f77ee08.png">

The first occurance of `static content` is the template, I guess.

**Comment by Tim-Erwin** [comment]
Just added another instance of `<my-component>` and with it got another "ghost" static content (making it four). So probably my assumption is wrong that it is the template that is visible here.

**Comment by Tim-Erwin** [comment]
And another observation: When using the web-component outside the app, it works as expected, no additional ghost.

**Comment by EisenbergEffect** [comment]
Thanks for the sample! I'll look at this over the weekend hopefully.

**Comment by Tim-Erwin** [comment]
I've used Aurelia for a while but I'm not at all familiar with the internals of the framework. I'd really like to help here. Are there any docs about the internal design which could help me get my feet wet?

**Comment by Tim-Erwin** [comment]
This only happens if - like in our example app - the `au-app` element is used. If I use a different element (`my-component`) and omit `au-app` from `index.ejs` the extra bits don't get rendered.

**Comment by EisenbergEffect** [comment]
I'm behind a bit, but wanted to let you know I haven't forgotten about this...
